<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test with firefox"
           tests="10"
           failures="1"
           errors="0"
           skipped="0"
           time="33.928">
  <properties />
            <testcase name="TC01_Check_UI_Component_Item_On_Introduce_Section" time="0.280" classname="testcase.Newsfeed.About.DetailsAboutYou.Testcase_PersonalAbout_OtherName">
                <failure type="java.lang.Throwable"
                  message="Mulitple failures (2):
Failure 1 of 2
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at Common.HelperFunction.AbstractTest.checkTrue(AbstractTest.java:119)
	at Common.HelperFunction.AbstractTest.verifyTrue(AbstractTest.java:131)
	at testcase.Newsfeed.About.DetailsAboutYou.Testcase_PersonalAbout_OtherName.TC01_Check_UI_Component_Item_On_Introduce_Section(Testcase_PersonalAbout_OtherName.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

Failure 2 of 2
java.lang.AssertionError: expected [true] but found [false]"
              >
                  <![CDATA[java.lang.Throwable: Mulitple failures (2):
Failure 1 of 2
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at Common.HelperFunction.AbstractTest.checkTrue(AbstractTest.java:119)
	at Common.HelperFunction.AbstractTest.verifyTrue(AbstractTest.java:131)
	at testcase.Newsfeed.About.DetailsAboutYou.Testcase_PersonalAbout_OtherName.TC01_Check_UI_Component_Item_On_Introduce_Section(Testcase_PersonalAbout_OtherName.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

Failure 2 of 2
java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:513)
  org.testng.Assert.assertTrue(Assert.java:42)
  org.testng.Assert.assertTrue(Assert.java:52)
  Common.HelperFunction.AbstractTest.checkTrue(AbstractTest.java:119)
  Common.HelperFunction.AbstractTest.verifyTrue(AbstractTest.java:131)
  testcase.Newsfeed.About.DetailsAboutYou.Testcase_PersonalAbout_OtherName.TC01_Check_UI_Component_Item_On_Introduce_Section(Testcase_PersonalAbout_OtherName.java:80)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:782)
  org.testng.TestRunner.run(TestRunner.java:632)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
  org.testng.SuiteRunner.run(SuiteRunner.java:268)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.run(TestNG.java:1064)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
                </failure>

          </testcase>
  
  
            <testcase name="TC10_Update_With_Othername_Contains_Specical_Character" time="3.323" classname="testcase.Newsfeed.About.DetailsAboutYou.Testcase_PersonalAbout_OtherName" />
                <testcase name="TC02_Check_User_Interactor_Component_Item_On_Introduce_Section" time="9.685" classname="testcase.Newsfeed.About.DetailsAboutYou.Testcase_PersonalAbout_OtherName" />
                <testcase name="TC06_Update_With_OtherName_Contains_Whitespace_On_Last_Position" time="2.733" classname="testcase.Newsfeed.About.DetailsAboutYou.Testcase_PersonalAbout_OtherName" />
                <testcase name="TC11_Update_With_Othername_Is_Uppercase" time="2.720" classname="testcase.Newsfeed.About.DetailsAboutYou.Testcase_PersonalAbout_OtherName" />
                <testcase name="TC12_Update_OtherName_With_Data_Is_Lowercase" time="2.715" classname="testcase.Newsfeed.About.DetailsAboutYou.Testcase_PersonalAbout_OtherName" />
                <testcase name="TC05_Update_With_OtherName_Contains_Whitespace_On_First_Position" time="2.848" classname="testcase.Newsfeed.About.DetailsAboutYou.Testcase_PersonalAbout_OtherName" />
                <testcase name="TC03_Update_With_Blank_OtherName" time="3.185" classname="testcase.Newsfeed.About.DetailsAboutYou.Testcase_PersonalAbout_OtherName" />
                <testcase name="TC09_Update_With_Othername_Contains_Number_And_Character" time="2.706" classname="testcase.Newsfeed.About.DetailsAboutYou.Testcase_PersonalAbout_OtherName" />
                <testcase name="TC08_Update_With_Othername_Contains_Only_Number" time="3.733" classname="testcase.Newsfeed.About.DetailsAboutYou.Testcase_PersonalAbout_OtherName" />
      
</testsuite>
